### ISSUE TITLE
Possibility of adding Seat Mó?

### ISSUE THREAD

**Issue by flixlix** [lorenzo-deluca/homeassistant-silence#3]
Hey!
I've purchased a Seat Mó Scooter and wanted to know if there is a possibility of adding it through this component. 
As far as I'm aware, the Seat Mó is almost the same scooter as the Silence Connected.
Thanks in advance

**Comment by lorenzo-deluca** [comment]
Hello Luca,
Yes, we can work on Seat Mó compatibility.. do you have experience with proxies?
You should use Postman (or similar) to sniff the Seat app webapi calls to figure out how to make the same calls with home assistant.

If you want you can contact me at me@lorenzodeluca.dev ;)

**Comment by lucasimons** [comment]
Are there any update of the integration for the Seat Mò? @flixlix @lorenzo-deluca

**Comment by lorenzo-deluca** [comment]
H everybody, thanks to @flixlix I was able to analyze the Seat application.

Unfortunately, the Seat app is better than the Silence app, and there is no way to intercept traffic.
I also tried to decompile it but it seems well obfuscated.
The only thing I was able to figure out is the service they use, which is this: https://giravolta.io, 
I sent an email to them (hello@giravolta.io) with the link to my project and proposed a collaboration but they still haven't responded.
If they give me access to their documentation, the implementation would be very simple.
possibly if you want to write to them as well.

if you want, since you are a Seat customer, you can writing to them putting the link to my project and asking if they can collaborate ;)

Thanks :)

**Comment by flixlix** [comment]
Closing as this is not possible at this point.
Thank you very much @lorenzo-deluca!

**Comment by killee** [comment]
I've asking them ;-)
Would it be better not to close this issue to be easy to find it?

**Comment by lorenzo-deluca** [comment]
> I've asking them ;-) Would it be better not to close this issue to be easy to find it?

Good idea ;)

**Comment by flixlix** [comment]
Does this mean we can now integrate Seat Mó Scooters?

**Comment by lorenzo-deluca** [comment]
Oh sorry @flixlix you're right, it's better to keep it open...!
I honestly haven't received any feedback (neither positive nor negative) from giravolta.io people.

Have any of you tried to contact them?

**Comment by flixlix** [comment]
I have also contacted them, but I also received no feedback 😔

**Comment by lucasimons** [comment]
> I have also contacted them, but I also received no feedback 😔

Now i have found this thesis that use a Seat API to implement some cripto payment, can you contact seat or the author of this thesis to find some new contact.

https://upcommons.upc.edu/bitstream/handle/2117/378984/Mobility_Service_Based_on_Blockchain_Technology.pdf?sequence=2

**Comment by Mocheto** [comment]
Hi there! 

I'm in the same scenario, waiting for seat mo compatibility, it would be great!

**Comment by Mocheto** [comment]
Hi, I've received news from SEAT, they no have public their API's, so we can not create an integration. They answer me about the possibility in next months, maybe as a roadmap for development team hearing our requests.

I've tried to open the seat mo apk and found some info pointing api.giravolta.io but not the real endpoint to access or credentials, if anyone has more information it would be great.

**Comment by lorenzo-deluca** [comment]
> Hi, I've received news from SEAT, they no have public their API's, so we can not create an integrateion. They answer me about the possibility in next monts, maybe as a roadmap for development team hearing our requests.
> 
> I've tried to open the seat mo apk and found some info pointing api.giravolta.io but not the real endpoint to access or credentials, if anyone has more information it would be great.

Hello, hope that SEAT will be open to third-party integration 👍 
I decompiled the apk and saw calls to api.giravolta.io
unfortunately app uses an embedded certificate to SSL validate the api server and it is not possible to sniff the payload with proxies or similar.

Anyway, the best solution is open third-party APIs

**Comment by lorenzo-deluca** [comment]
Hello everyone @flixlix , @Mocheto, @lucasimons , @killee  
I am writing here to inform you that I am working, with other guys, on an alternative project that creates its own private server to point the GPS module to and not be dependent on Silence and Seat services, also because Silence is starting to charge for the App service on a subscription basis.

The project is this: [silence-private-server](https://github.com/lorenzo-deluca/silence-private-server)
It require small hardware skills because you have to connect to the module via serial (from the OBD port) to change the pointing to the server (we are working on Bluetooth app for reconfigure Astra module, stay tuned :) )

It should work on both Silence and Seat, if you want to try it let me know.
